name: DeployAPI

on:
    push:
        branches: [main, release/**, next/**]

jobs:
    api:
        runs-on: ngdil-runner

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: "https://registry.npmjs.org"

            - name: Install Dependencies
              run: |
                  echo "installing pnpm"
                  npm install -g pnpm
                  echo "installing deps for packages"

            - name: build server
              run: |
                  rm -rf /var/www/ngdilstaging/api/*
                  cp -R ./server/* /var/www/ngdilstaging/api/
                  cd /var/www/ngdilstaging/api/
                  pnpm i

            - name: start application
              continue-on-error: true
              run: |
                  pm2 restart "ngdil-api"
