name: "Lint Code"

on:
  pull_request:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          echo "installing pnpm"
          npm install -g pnpm
          echo "installing deps for packages"
          pnpm i

      - name: Lint
        run: pnpm --filter=* run lint
